Repository ppc64le-cloud/k8s-ansible, pull requests merged in 2022-09, with the labels that each got.

#43 Fix the prereq for the container runtime
  roles/runtime/tasks/containerd.yaml
  roles/runtime/tasks/main.yaml
Labels: lgtm, approved, size/M

#44 Calico Version variable and change to download manifest
  group_vars/all
  roles/install-calico/files/calico.yaml
  roles/install-calico/tasks/main.yml
Labels: lgtm, approved, size/XXL

#45 Set bind-address for controller-manager and scheduler to 0.0.0.0 and RBAC for /metrics API
  roles/install-calico/tasks/main.yml
  roles/install-k8s/templates/kubeadm.yaml.j2
  roles/perf-cluster-tasks/tasks/main.yml
Labels: lgtm, approved, size/S, tide/merge-method-squash
