Repository ppc64le-cloud/k8s-ansible, pull requests merged in 2023-03, with the labels that each got.

#50 Cleanup: Remove deprecated field `container-runtime` and configure containerRuntimeEndpoint through kubeadm.yaml
  roles/install-k8s/templates/kubeadm.yaml.j2
  roles/runtime/files/containerd/dropin.conf
  roles/runtime/tasks/containerd.yaml
Labels: lgtm, approved, size/S

#51 Add task to disable checksum offload on default network interface
  roles/install-k8s/tasks/main.yml
Labels: size/XS, lgtm, approved

#52 Add support for CRI-O container runtime.
  group_vars/all
  roles/install-k8s/tasks/main.yml
  roles/install-k8s/templates/kubeadm.yaml.j2
  roles/runtime/files/crio/crio.service
  roles/runtime/files/crio/policy.json
  roles/runtime/tasks/crio.yaml
  roles/runtime/tasks/main.yaml
  roles/runtime/templates/crictl/crictl.yaml.j2
Labels: lgtm, approved, size/L

#53 Add task to pre-pull images and update PodSandbox Image.
  group_vars/all
  install-k8s-perf.yml
  roles/runtime/tasks/main.yaml
  roles/runtime/templates/containerd/config.toml.j2
Labels: lgtm, approved, size/S

#54 Fix for pre-pulling images.
  install-k8s-perf.yml
Labels: size/XS, lgtm, approved
