Repository ppc64le-cloud/k8s-ansible, pull requests merged in 2024-11, with the labels that each got.

#76 Ansible playbook added for knative & tekton
  group_vars/all
  install-k8s-kn-tkn.yml
  roles/install-nfs/files/class.yaml
  roles/install-nfs/files/rbac.yaml
  roles/install-nfs/tasks/main.yaml
  roles/install-nfs/templates/nfs-client-provisioner.yaml.j2
Labels: lgtm, approved, size/L

#79 Add playbook and task for k8s UT job
  k8s-ut-remote.yml
  roles/k8s-ut/tasks/main.yml
Labels: lgtm, approved, size/M

#80 Add pre-check to conditionally remove control-plane taint
  roles/install-nfs/tasks/main.yaml
Labels: size/XS, lgtm, approved
